apiVersion: v1
kind: Service
metadata:
  name: stundenplan-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: stundenplan-app
    type: back-end
