apiVersion: v1
kind: Service
metadata:
  name: stundenplan-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: stundenplan-app
    type: front-end