apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: webserver-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: stundenplan-webserver
    type: front-end