apiVersion: batch/v1
kind: Job
metadata:
     name: mysql-dump
     namespace: default
spec:
  template:
    metadata:
      name: import-mysql
    spec:
      restartPolicy: Never
      initContainers:
        - name: init-mydb
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup mysql-service.default.svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
      containers:
        - name: mysql-dump
          image: mysql:5.6.48
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password

            - name: MYSQL_ROOT_HOST
              value: "%"

            - name: MYDB_HOST
              value: "mysql-service"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-database
          command:
            - "bash"
            - "-c"
            - 'mysql -u${MYSQL_USER} -p${MYSQL_ROOT_PASSWORD} -h ${MYDB_HOST} ${MYSQL_DATABASE} < /tmp/initdb.sql'
          volumeMounts:
            - mountPath: /tmp/initdb.sql
              subPath: initdb.sql
              name: mysql-dump
              readOnly: false
      volumes:
        - name: mysql-dump
          configMap:
            name: mysql-initdb-config
