apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-storage
  resources:
    requests:
      storage: 500Mi