apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
data:
  mysql-root-password: cm9vdA==
  mysql-database: c3R1bmRlbnBsYW4=
  mysql-user: cm9vdA==
  mysql-password: cm9vdA==