apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: cpuguy83/nfs-server
          securityContext:
              privileged: true
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          args:
            # Pass the paths to share to the Docker image
            - /exports
