---
- name: create storageClass for mysql
  k8s:
    state: present
    definition: "{{ lookup('file', '../../../../kubernetes/storageClasses-definition/storage-class-def.yml') }}"

- name: create PVC for mysql
  k8s:
    state: present
    definition: "{{ lookup('file', '../../../../kubernetes/PVC-definitions/mysql-pvc-def.yml') }}"

- name: create secret for mysql
  k8s:
    state: present
    definition: "{{ lookup('file', '../../../../kubernetes/secret-definitions/mysql-secret.yml') }}"

- name: create sql dump configmap for mysql
  k8s:
    state: present
    definition: "{{ lookup('file', '../../../../kubernetes/configmap-definition/mysql-initdb-config.yml') }}"

- name: create deployment for mysql
  k8s:
    state: present
    definition: "{{ lookup('file', '../../../../kubernetes/deployment-definitions/mysql-deployment-def.yml') }}"

- name: create service for mysql
  k8s:
    state: present
    definition: "{{ lookup('file', '../../../../kubernetes/service-definitions/mysql-service-definition.yml') }}"
- name: import data mysql
  k8s:
    state: present
    definition: "{{ lookup('file', '../../../../kubernetes/jobs-definition/mysql-dump-job.yml') }}"