---
#- hosts: localhost
#  connection: local
#  roles:
#    - init-cluster

- hosts: gcp_root
  vars_files:
    - ./vars/vault.yml
#  roles:
#    - install-gcloud
  tasks:
#    - include: ./includes/install-docker/install_docker.yml
#    - include: ./includes/nginx/build_nginx_image.yml
#    - include: ./includes/php/build_php_image.yml
#    - include: ./includes/kubernetes/mysql-service/mysql-service.yml
    - include: ./includes/kubernetes/nfs-service/nfs-service.yml
    - include: ./includes/kubernetes/stundenplan-service/stundenplan-service.yml
#    - include: ./includes/kubernetes/webserver-service/webserver-service.yml