---
- hosts: server-node
  vars_files:
    - ./vars/vault.yml
  roles:
   - nfs-provisioner
  tasks:
   - include: ./includes/kubernetes/mysql-service/mysql-service.yml
   - include: ./includes/kubernetes/stundenplan-service/stundenplan-service.yml