---
- hosts: gcp_root
  vars_files:
    - ./vars/vault.yml
  tasks:
    - include: ./includes/kubernetes/mysql-service/mysql-service.yml
    - include: ./includes/kubernetes/stundenplan-service/stundenplan-service.yml