---
- hosts: localhost
  vars_files:
    - ./vars/vault.yml
  connection: local
  tasks:
    - include: ./includes/install-private-ssh-key/install-private-ssh-key.yml
- hosts: gcp_root
  vars_files:
    - ./vars/vault.yml

  tasks:
    - include: ./includes/install-docker/install_docker.yml