---
- name: generate auth
  template:
    src: tmpl.json
    dest: "{{auth_file_path}}"
- name: create a cluster
  gcp_container_cluster:
    name: "{{cluster_name}}"
    initial_node_count: "{{number_of_nodes}}"
    master_auth:
      username: "{{master_username}}"
      password: "{{master_password}}"
    node_config:
      machine_type: "{{machine_type}}"
      disk_size_gb: "{{disk_size}}"
    zone: "{{zone}}"
    location: "{{location}}"
    project: "{{project_id}}"
    auth_kind: serviceaccount
    service_account_file: "{{auth_file_path}}"
    state: present
  register: cluster
- name: create a node pool
  gcp_container_node_pool:
    name: my-pool
    config:
      machine_type: "{{machine_type}}"
    initial_node_count: "{{number_of_nodes}}"
    cluster: "{{cluster}}"
    location: "{{location}}"
    project: "{{project_id}}"
    auth_kind: serviceaccount
    service_account_file: "{{auth_file_path}}"
    state: present

- name: create a firewall Rule
  gcp_compute_firewall:
    name: kuberenetes-nodeports
    allowed:
      - ip_protocol: tcp
        ports:
          - "30000-32767"
    project: "{{project_id}}"
    auth_kind: serviceaccount
    service_account_file: "{{auth_file_path}}"
    state: present

- name: remove auth file
  file:
    path: "{{auth_file_path}}"
    state: absent
